lib/src/common/model/issues.dart
Context: I've hit this NPE when trying to migrate issues with [github-issue-mover.appspot.com](http://github-issue-mover.appspot.com), for instance nativelibs4java/Scalaxy#18.
=> Guard against null labels when decoding Issue from JSON

lib/src/common/util/pagination.dart
Oops...
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/directmyfile/github.dart/58)
=> fix NPE in pagination

.gitignore
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/directmyfile/github.dart/62)
=> ignore .packages, cleanup other ignores

lib/src/common/github.dart, lib/src/common/util/errors.dart
to get more informative exceptions.
I run into a 403 (API rate limit exceeded) but the exception only told me `UnknownError`
=> Forward error message of the response to `UnknownError`

CHANGELOG.md, lib/src/common/github.dart, pubspec.yaml
@kaendfinger Cool?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/directmyfile/github.dart/65)
=> Ratelimit fun

CHANGELOG.md, lib/src/common/issues_service.dart, lib/src/common/model/issues.dart
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/directmyfile/github.dart/66)
=> A few more, targeted features

CHANGELOG.md, lib/src/common/git_service.dart, lib/src/common/model/git.dart, lib/src/common/model/issues.dart
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/directmyfile/github.dart/67)
=> Add Milestone.id

lib/src/common/model/pulls.dart
It was accidentally set to 'head'
@kaendfinger
=> fix 'base' field deserialization

lib/src/common/issues_service.dart
Extended issue listing APIs to support filtering per milestone
=> Add support for listing issues per milestone

lib/src/common.dart, lib/src/common.g.dart, lib/src/common/github.dart, lib/src/common/model/pulls.dart, lib/src/common/model/repos.dart, lib/src/common/model/repos_contents.dart, lib/src/common/repos_service.dart, pubspec.yaml, test/data_object_test.dart
Please do a rebase-merge w/ these!
=> Cleanup, getLicense, getResponseData helper

pubspec.yaml
This just updates the version to 4.0.0 in prep for a versioned release.
=> Update version for 4.0.0 release

README.md
=> update documented dependency version to latest

analysis_options.yaml
=> de-dup lints

lib/src/common/model/repos_commits.dart
=> fix casts in repos_commits parsing

lib/src/common/pulls_service.dart
I'd like to be able to change the base repository on PRs.
=> Add base to PR edit

CHANGELOG.md, pubspec.yaml
After reviewing and merging outstanding PRs, this updates the changelog and version for a follow up 5.0.1 release.
=> update changelog, version to 5.0.1

lib/src/common/activity_service.dart
fixes https://github.com/DirectMyFile/github.dart/issues/143
=> Fix pollPublicEventsReceivedByUser to use the correct API URL

lib/src/common/pulls_service.dart
ListFiles has the wrong return type and fails at runtime.  This fixes it.
=> fix listFiles

lib/src/common/issues_service.dart
Crashes at runtime right now - I think this kind of cast was valid at some point before Dart 2.0 but isn't anymore.
=> Fix casts on addLabelsToIssue

lib/src/common/model/pulls.dart
This adds the draft status of a PR to the model.
Fixes #161
=> Adding draft property to PR model

lib/src/common/model/pulls.dart
This adds labels to pull requests. It's just a refinement of https://github.com/DirectMyFile/github.dart/pull/155 with some additional null handling
=> Add access to labels on Pull Requests

lib/src/common/model/pulls.dart
PRs have labels on them - this adds access to them.  I'm not 100% sure which class this is supposed to go on, so I picked the one that seems safest (and the one I need :)).
=> Add labels to PRs

CHANGELOG.md, pubspec.yaml
Preparing for the 5.2.0 release
- bump version
- update changelog
- longer description for more points
=> Preparing for the 5.2.0 release

lib/src/common/issues_service.dart
Fixes https://github.com/SpinlockLabs/github.dart/issues/179
=> Fix to correctly return Future<Issue>

lib/src/common/activity_service.dart
Already done formatting with `dartfmt`.
Maybe use `StatusCodes.RESET_CONTENT` instead of `205` would be better?
=> Implemented `markThreadRead`

lib/src/common/activity_service.dart
I thought that must be someone's copy/paste mistake.
=> Fix wrong service API with events received by user.

CHANGELOG.md, lib/src/common/model/repos_contents.dart, pubspec.yaml
=> Fix GitHubFile.text decoding

CHANGELOG.md, lib/src/common/github.dart, pubspec.yaml
This fixes https://github.com/SpinlockLabs/github.dart/issues/196
=> Addresses https://github.com/SpinlockLabs/github.dart/issues/196

CHANGELOG.md, lib/src/common/github.dart, pubspec.yaml
Fixes https://github.com/SpinlockLabs/github.dart/issues/199
=> Handle calling List.from with null

lib/src/common/activity_service.dart, lib/src/common/gists_service.dart, lib/src/common/git_service.dart, lib/src/common/issues_service.dart, lib/src/common/misc_service.dart, lib/src/common/orgs_service.dart, lib/src/common/pulls_service.dart, lib/src/common/repos_service.dart, lib/src/common/users_service.dart, lib/src/common/util/oauth2.dart, lib/src/json.dart, lib/src/server/hooks.dart, lib/src/util.dart, test/data_object_test.dart, test/experiment/error_handling.dart, test/git_test.dart
This PR should fix #211.
It adds a top-level class with an `encode` method that handles Json encoding.
This method automatically delete null fields if the object to encode is a Map.
Also, it automatically converts dates objects to the right string representation.
=> Specific Json encoder

lib/src/common/model/users.dart, lib/src/common/model/users.g.dart, lib/src/common/repos_service.dart
Seems the contributors' response are different from the User.
Link: https://developer.github.com/v3/repos/#response-if-repository-contains-content
=> Fix contributors response

lib/src/common/model/users.dart, lib/src/common/model/users.g.dart
Add the new `twitter_username` property to `User`
see https://developer.github.com/v3/users/
=> Add User#twitter_username property

example/releases.dart
since https://github.com/Workiva/wdesk seems to no longer exist or went private
=> pick an existing repo for examples/releases

example/common.dart
since `directcode.org` seems to be not available atm
prob need to clear with @DirectMyFile team if they still gonna maintain it
=> view-source now navigates directly to github-repo

lib/src/common/util/oauth2.dart
=> Doc comment fix - fixing #193

CHANGELOG.md, lib/src/common/model/checks.dart, pubspec.yaml, test/unit/checks_test.dart
Added the conclusion property to be a member variable of checkRun class. 
Solved the https://github.com/flutter/flutter/issues/99850 issue.
=> Add conclusion property to CheckRun

README.md
=> test auto-release

README.md
=> test PR for auto-release

lib/src/common/model/checks.dart, test/unit/checks_test.dart
Implement toString in CheckRun. This is a convenience for our work in the flutter auto_submit bot so that we can see the data that is being passed into the API.
=> Add support for toString to the Checkrun object.

.github/workflows/label_prs.yml, .github/workflows/triage.yml
github-script v3 was in use and stopped working. So updating to the latest version seems to fix things.
=> Update to github-script 6

pubspec.yaml
Need to update the package version for release.
=> Update package version

CHANGELOG.md, lib/src/common/github.dart, pubspec.yaml, test/common/github_test.dart
See https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#user-agent-required
=> Add required UserAgent HTTP header

.github/workflows/label_prs.yml, .github/workflows/require_semver_label.yml
=> for testing

lib/src/common/repos_service.dart, test/common/data/repos_json.dart, test/common/repos_service_test.dart
https://github.com/flutter/flutter/issues/124763
Implements the query params from https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository
=> Add optional filter params on Repositories.listCommits

lib/src/common/github.dart
Follow up from https://github.com/SpinlockLabs/github.dart/pull/377#issuecomment-1605083567
Re-add the ability to change auth instead of recreating the client.
=> Revert immutable auth

CHANGELOG.md, lib/src/common/misc_service.dart, lib/src/common/model/misc.dart, lib/src/common/model/misc.g.dart, pubspec.yaml, test/common/misc_service_test.dart
Fixes https://github.com/SpinlockLabs/github.dart/issues/373
* This is mostly to test the new release process on something that isn't urgent
=> Update MiscService.getApiStatus to v2

lib/src/common/model/issues.dart
Fixes https://github.com/SpinlockLabs/github.dart/issues/401
=> Fix case sensitivity in Issue.[isOpen, isClosed]
