README.md
lib/src/common/util/pagination.dart
pubspec.yaml

Also note: you should encourage folks to use a wider version range on your package.
You should release `3.0.0` if you ever make breaking changes to the API.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/directmyfile/github.dart/59)

Fix for empty link response header

---

lib/src/common/gists_service.dart

The public parameter doesn't seem to do anything. I made the files paramater optinal, as it is possible to not edit any files, but just edit the description.

remove `public` parameter from editGist and make `files` parameter optional

---

lib/src/common/repos_service.dart

The GitHub API has an optional parameter for commit/branch/tag on the `getReadme()` and `getContents()` functions. This PR adds this.
*BTW: It's been a while - so, hello again!*

Add optional parameter for the commit/branch/tag

---

lib/server.dart

`req.write(request.body)` might fail because of encoding issue. It is better to propagate the error back to the caller for debugging.

Propogate error back to the caller

---

lib/browser.dart
lib/src/common/util/errors.dart

It appears that in v3.0.0, a switch was made to use the `http` package. By default, this package uses an IOClient (dependent on `dart:io`). In order to use the `http` package in the browser, you have to import the `browser_client.dart` entry point and use that client instead of the default one.
When constructing an instance of `GitHub`, a `Client` can be passed in, but if it isn't, it will construct the default `Client` from the `http` package (see https://github.com/DirectMyFile/github.dart/blob/master/lib/src/common/github.dart#L50). In other words, if you don't pass in an instance of `Client`, the resulting `GitHub` instance will not work in the browser because it will be using an `IOClient`.
Unfortunately, the `browser.dart` entry point for this package does not pass in a …

Fix usage in browser

---

lib/src/common/pulls_service.dart

While attempting to pull down closed pull requests, I noticed this was not possible as I could not specify the 'state' of the pull requests I wanted to retrieve.  Several other supported parameters are not included in this implementation. (https://developer.github.com/v3/pulls/#list-pull-requests )
This pr fixes this issue by including these additional parameters.
For your consideration : 
@kaendfinger @kevmoo @Pacane @marcojakob

Updated options for list method.

---

lib/src/common/pulls_service.dart

We would like to create a pull request.  It seems fairly intentional for us to use the pulls_service.dart, yet when we look at the `create` method, it seems to imply creating a release, not a pull request?
```dart
/// Creates a Pull Request based on the given [request].
///
/// API docs: https://developer.github.com/v3/pulls/#create-a-pull-request
Future<PullRequestInformation> create(
RepositorySlug slug, CreateRelease request) {
return _github.postJSON("/repos/${slug.fullName}/pulls",
convert: PullRequestInformation.fromJSON,
body: request.toJSON()) as Future<PullRequestInformation>;
}
```
( from https://github.com/DirectMyFile/github.dart/blob/ef26ddf899ba725e88b8b1ad6323d30218c85867/lib/src/common/pulls_service.dart#L23 )
It seems like this method should be using the …

fix for creating a pull request.

---

.travis.yml

This adds an initial .travis.yml file to run Travis CI. 
It currently avoids running dart analyzer on the example directory as it seems that there are errors in master and will be fixed in a separate PR.
The tests are currently commented out and will be enabled in a separate PR with test fixes.

Add basic Travis CI run

---

lib/src/server/hooks.dart

An upcoming change to the Dart SDK will change `HttpRequest` and
`HttpClientResponse` from implementing `Stream<List<int>>` to
implementing `Stream<Uint8List>`.
This forwards-compatible change prepares for that SDK breaking
change by casting the Stream to `List<int>` before transforming
it.
https://github.com/dart-lang/sdk/issues/36900

Prepare for upcoming change to HttpRequest and HttpClientResponse

---

README.md

Now that v5 is released, update the readme to suggest using that version.

Update readme to use ^5.0.0

---

lib/src/common/github.dart
lib/src/common/repos_service.dart

I was trying to use this API but ended up with `Not Found` messages. While debugging, I've discovered [`updatefile`](https://developer.github.com/v3/repos/contents/#create-or-update-a-file) request must be done with `PUT` command (and not `POST`, as this library was doing).
Warning: there may be otherrequests that must be done with `PUT` method!

updateFile request must be a PUT

---

CHANGELOG.md
lib/src/common/model/repos_releases.dart
lib/src/common/model/repos_releases.g.dart
pubspec.yaml

This fixes the naming of targetCommitsh to targetCommitish in a non-breaking way.

Fix naming targetCommitsh to targetCommitish

---

lib/src/common/github.dart
lib/src/common/model/repos_releases.dart
lib/src/common/model/repos_releases.g.dart

@ThinkDigitalSoftware I made a couple of adjustments. Let me know what you think.
- I filled out a little more information for the deprecations and ignored them for JSON serialization.
- I added some more information in the dartdoc comments for what you can pass in for the body of a request.
- I flipped the check when setting the body. It sets the body bytes if it is a List<int> and everything else is converted to a string and set as text content.
Would you be willing to give this a quick test for your use case to make sure it works for you?

Adjust deprecations and binary uploads

---

lib/src/common/repos_service.dart

Adjust the recent awesome additions to be non-breaking changes.
- Change methods that return `Future<void>` back to `Future<bool>`. Made changes to have it either actually return a future true if it succeeds, or it will throw with an error. It still won't ever swallow the response / error and just return a future false if it fails. 
- Restored the original signature of `createDeployKey` and added a new method `createDeployKeyFromStrings` that takes the title and key as Strings
@axel-op Will you give this branch a smoke test to see if the changed methods work for you?
If things are looking good, I'll update the changelog and get this out as the next 5x release.

Make new additions non-breaking

---

lib/src/common/github.dart

Rate limiting information was being gathered but never used to actually wait.
This change will wait until rate limit reset before sending a request to the GitHub API.

Implement rate-limiting

---

lib/src/common/github.dart
lib/src/common/util/errors.dart
lib/src/common/util/pagination.dart

When the GitHub API replies with a server error (usually HTTP 502), retry up to `maxServerErrors` times with `serverErrorBackOff` intervals in between.
Currently, the inputs above are constants: each request will tolerate at most 10 errors and will wait 10 seconds between each attempt (this is _in addition_ to any rate limiting imposed by the GitHub API). If needed, it is easy enough to add both as optional arguments to `fetchStreamed`.
This is important for long-running batch jobs. Without this change, the package will just crash any time it encounters a GitHub HTTP 50x error (which are rare, but not unheard of), losing any pagination progress.

Back off when server fails (HTTP 50x)

---

lib/github.dart
lib/github_stub.dart

Imitate the way http is written, let the createGitHubClient method work on dart vm, flutter and web.

Make method createGitHubClient support vm flutter and web.

---

CHANGELOG.md
lib/src/common/model/repos_contents.dart
lib/src/common/model/repos_contents.g.dart
pubspec.yaml

Looks like a class was missed that wasn't made json serializable. I'm hoping this fixes https://github.com/SpinlockLabs/github.dart/issues/190
It should be converted either way.

make RepositoryContents json serializable

---

lib/src/common/github.dart
lib/src/common/issues_service.dart
lib/src/common/model/reaction.dart
lib/src/util.dart
test/experiment/reactions.dart

According to https://developer.github.com/v3/reactions/#list-reactions-for-an-issue it can take an optional `content` parameter to filter reactions by that reaction. This PR adds that capability.
Strangely, it works for all reactions except for +1 and -1. I assume due to the URL encoding of the + and - signs. I've tried multiple different ways of encoding and the github API always seems to fail with `Variable $content of type ReactionContent was provided invalid value`. At this point, I'm wondering if there's a decoding issue on github's side for this API.
Tried:
```
curl --header "Accept:application/vnd.github.squirrel-girl-preview+json"  https://api.github.com/repos/SpinlockLabs/github.dart/issues/177/reactions\?content\=+1
curl --header …
```

Add content param to listReactions for issues

---

lib/src/common/model/pulls.dart
lib/src/common/model/pulls.g.dart
lib/src/common/pulls_service.dart

In order to create a draft PR using Github's REST API, you have to add a special header:
```
application/vnd.github.shadow-cat-preview+json
```
To facilitate this, I added a new bool field to the `CreatePullRequest` class, and when it is true, the call made by `PullRequestService.create` updates the value of `preview` accordingly.
FYA @robbecker-wf

Add support for creating draft PRs

---

lib/src/common.dart
lib/src/common/checks_service.dart
lib/src/common/github.dart
lib/src/common/model/checks.dart
lib/src/common/repos_service.dart
lib/src/common/util/json.dart
lib/src/common/util/pagination.dart
lib/src/common/util/utils.dart

This is a non-breaking PR. 
I have implemented some methods to interact with the Checks API (https://developer.github.com/v3/checks) for my personal use, I thought I could make this draft PR to merge them later.

Methods for Checks API

---

README.md

That way the pub.dev front page will have a link to the source of the demos.

Link to example/ directory from README

---

lib/src/common/model/repos.dart
lib/src/common/model/repos.g.dart

This will throw an exception when calling
`GitHub().activity.listEventsPerformedByUser(username)`

Nullable hasPages

---

CHANGELOG.md
lib/src/common/misc_service.dart
lib/src/common/model/misc.dart
pubspec.yaml

Querying `/` uses quota to find the rate limit. Moving to `/rate_limit` does not use quota.

Switch to dedicated rate_limit endpoint

---

CHANGELOG.md
lib/src/common/model/repos_releases.dart
lib/src/common/model/repos_releases.g.dart
lib/src/common/repos_service.dart
lib/src/server/hooks.dart
pubspec.yaml
test/server/hooks_test.dart

- Added `generateReleaseNotes` boolean to CreateRelase class to have github auto-create release notes
- Added `generateReleaseNotes` method to RepositoriesService to have github create release notes
between to tags (without creating a release) and return the name and body. This is helpful when you want to add the release notes to a CHANGELOG.md before making the actual release

Add: Auto release notes & generateReleaseNotes API

---

CHANGELOG.md
lib/src/common/model/checks.dart
lib/src/common/util/utils.dart
pubspec.yaml

This value is null until check run is complete (so you're supposed to rely on the status if this is null)
Fixes https://github.com/SpinlockLabs/github.dart/issues/277

Make CheckRunConclusion nullable

---

CHANGELOG.md
lib/src/common/model/repos.dart
lib/src/common/model/repos.g.dart
pubspec.yaml
test/src/mocks.mocks.dart

This is to support https://github.com/SpinlockLabs/github.dart/issues/283 by adding the files field in GitHubComparison.
https://docs.github.com/en/rest/reference/commits#compare-two-commits

Add files field in Git commit comparison

---

lib/src/common/model/gists.dart
lib/src/common/model/gists.g.dart
lib/src/common/model/misc.dart
lib/src/common/model/misc.g.dart
lib/src/common/model/notifications.dart
lib/src/common/model/notifications.g.dart
lib/src/common/model/orgs.dart
lib/src/common/model/orgs.g.dart
lib/src/common/model/repos.dart
lib/src/common/model/repos.g.dart
lib/src/common/model/search.dart
lib/src/common/model/search.g.dart
lib/src/common/model/users.dart
lib/src/common/model/users.g.dart

Fixes #288 
The type of the files when getting a gist isn't a list, it is a map. This is a breaking change. So anywhere you were accessing the files from a gist before, you'll need to update your code to expect a map.
**Breaking change:** In the Gist class, the old type of files was
```dart
List<GistFile>? files;
```
and the new type is
```dart
Map<String, GistFile>? files;
```
**Breaking change:** In the GistFile class, the name property is now filename
While I was in there I noticed there were a lot of files that don't generate the toJson method. It doesn't hurt to generate those so I updated all the places that weren't generating toJson.

Fix getting gists

---

lib/src/common/model/checks.dart
test/unit/checks_test.dart

The flutter team needs a new state to support skipping stable tests in presubmit pull requests.

Added a new conclusion state to support flutter autosubmit bot

---

.github/workflows/publish_release.yml

Temporarily moving this to a forked version of the action with the fix. When https://github.com/sakebook/actions-flutter-pub-publisher/pull/34 is merged, we can revert back to the upstream.

Fix publish release workflow

---

CHANGELOG.md
lib/src/common/model/checks.dart
pubspec.yaml
test/unit/checksuite_test.dart

This field is part of the "check_suite" object as seen here: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=rerequested#check_run
Although the `head_sha` usually provides enough information, it is useful to know which branch was targeted when the checkrun was rerequested.
<details>
<summary>Image</summary>
</details>

Add "head_branch" field to CheckSuite object

---

CONTRIBUTING.md
lib/src/common/github.dart

I run into these prints sometimes when using this package, and they mess up the "pretty" UI of my CLI app. :-)

Avoid printing messages to the console.

---

example/index.dart
example/user_info.dart
lib/src/browser/xplat_browser.dart
lib/src/common/github.dart
lib/src/common/util/auth.dart
lib/src/common/xplat_common.dart
lib/src/server/xplat_server.dart
test/common/github_test.dart
test/experiment/crawler.dart
test/git_test.dart
test/scenarios_test.dart

For the most part, this is already non-nullable.
See https://github.com/flutter/flutter/issues/129134 - This should help with debugging why our server is getting a null auth state.

Make GitHub.auth non-nullable

---

lib/src/common/github.dart
lib/src/common/util/auth.dart

Also added `authorizationHeaderValue()` function.
Also added `const` qualifier to `basic` constructor.

Add bearerToken constructor to Authentication class

---

CHANGELOG.md
lib/src/common/model/git.dart
lib/src/common/model/git.g.dart
lib/src/common/model/repos.dart
lib/src/common/model/repos.g.dart
lib/src/server/hooks.dart
lib/src/server/hooks.g.dart
test/data_object_test.dart

* This adds some of the information for the [PushEvent](https://docs.github.com/en/webhooks/webhook-events-and-payloads#push) from Github
* Additionally, created `PushGitCommit` that contains some data for the list of commits and head commit for `PushEvent`

Add the 'PushEvent' webhook and associated PushCommit object

---

.github/workflows/dart.yml
CHANGELOG.md
analysis_options.yaml
lib/src/common.dart
lib/src/common/activity_service.dart
lib/src/common/authorizations_service.dart
lib/src/common/checks_service.dart
lib/src/common/gists_service.dart
lib/src/common/git_service.dart
lib/src/common/issues_service.dart
lib/src/common/misc_service.dart
lib/src/common/model/checks.dart
lib/src/common/orgs_service.dart
lib/src/common/pulls_service.dart
lib/src/common/repos_service.dart
lib/src/common/search_service.dart
lib/src/common/url_shortener_service.dart
lib/src/common/users_service.dart
lib/src/common/util/errors.dart
lib/src/common/util/utils.dart
pubspec.yaml
test/helper/http.dart
test/server/hooks_test_data.dart
tool/process_github_schema.dart

- require Dart 3.0
- update to the latest `package:lints`
- address new lints (and two existing lint issues, which were causing red bots)

require dart 3.0; update to the latest package:lints

---

CHANGELOG.md
lib/src/common/util/pagination.dart
pubspec.yaml
test/common/repos_service_test.dart
test/git_test.dart

Fixes https://github.com/SpinlockLabs/github.dart/issues/414

Fix pagination logic to use `next` link

---

lib/src/common/model/checks.dart
test/unit/checks_test.dart

Creating a new concolusion with the GitHub API and then encoding that CheckRun to json adds: `"conclusion":"null"` to the json string; attempting to decode that throws an exception.
Fixes #412

Handle 'null' conclusion
